### Packages & Libraries

In [39]:
install.packages("dplyr")
install.packages("questionr")
library(dplyr)
library(questionr)

Warning message:
"package 'dplyr' is in use and will not be installed"
Warning message:
"package 'questionr' is in use and will not be installed"

### Upload the datasets

In [40]:
setwd('C:/Users/Carlos/Documents/Varios/OnPremise/Datasets/TimeSeries')
air_visit <- read.csv(".\\air_visit_data.csv", header=T, na="")
date_info <- read.csv(".\\date_info.csv", header=T, na="")

In [41]:
air_visit

       air_store_id         visit_date visitors
1      air_ba937bf13d40fb24 2016-01-13 25
2      air_ba937bf13d40fb24 2016-01-14 32
3      air_ba937bf13d40fb24 2016-01-15 29
4      air_ba937bf13d40fb24 2016-01-16 22
5      air_ba937bf13d40fb24 2016-01-18  6
6      air_ba937bf13d40fb24 2016-01-19  9
7      air_ba937bf13d40fb24 2016-01-20 31
8      air_ba937bf13d40fb24 2016-01-21 21
9      air_ba937bf13d40fb24 2016-01-22 18
10     air_ba937bf13d40fb24 2016-01-23 26
11     air_ba937bf13d40fb24 2016-01-25 21
12     air_ba937bf13d40fb24 2016-01-26 11
13     air_ba937bf13d40fb24 2016-01-27 24
14     air_ba937bf13d40fb24 2016-01-28 21
15     air_ba937bf13d40fb24 2016-01-29 26
16     air_ba937bf13d40fb24 2016-01-30  6
17     air_ba937bf13d40fb24 2016-02-03 18
18     air_ba937bf13d40fb24 2016-02-04 12
19     air_ba937bf13d40fb24 2016-02-05 45
20     air_ba937bf13d40fb24 2016-02-06 15
21     air_ba937bf13d40fb24 2016-02-08 19
22     air_ba937bf13d40fb24 2016-02-09 15
23     air_ba937bf13d40fb24 2016-02-10 32
24     air_ba937bf13d40fb24 2016-02-11  3
25     air_ba937bf13d40fb24 2016-02-12 26
26     air_ba937bf13d40fb24 2016-02-13  8
27     air_ba937bf13d40fb24 2016-02-15 14
28     air_ba937bf13d40fb24 2016-02-16 15
29     air_ba937bf13d40fb24 2016-02-17 17
30     air_ba937bf13d40fb24 2016-02-18 22
...    ...                  ...        ...
252079 air_24e8414b9b07decb 2017-03-17  4
252080 air_24e8414b9b07decb 2017-03-18  7
252081 air_24e8414b9b07decb 2017-03-21  2
252082 air_24e8414b9b07decb 2017-03-22  8
252083 air_24e8414b9b07decb 2017-03-23  8
252084 air_24e8414b9b07decb 2017-03-24  7
252085 air_24e8414b9b07decb 2017-03-25  2
252086 air_24e8414b9b07decb 2017-03-27  4
252087 air_24e8414b9b07decb 2017-03-28  7
252088 air_24e8414b9b07decb 2017-03-29 11
252089 air_24e8414b9b07decb 2017-03-30  7
252090 air_24e8414b9b07decb 2017-03-31  8
252091 air_24e8414b9b07decb 2017-04-01  6
252092 air_24e8414b9b07decb 2017-04-03  4
252093 air_24e8414b9b07decb 2017-04-04  2
252094 air_24e8414b9b07decb 2017-04-05  2
252095 air_24e8414b9b07decb 2017-04-06  8
252096 air_24e8414b9b07decb 2017-04-07  8
252097 air_24e8414b9b07decb 2017-04-08  8
252098 air_24e8414b9b07decb 2017-04-10  4
252099 air_24e8414b9b07decb 2017-04-11  2
252100 air_24e8414b9b07decb 2017-04-12  8
252101 air_24e8414b9b07decb 2017-04-13  6
252102 air_24e8414b9b07decb 2017-04-14  2
252103 air_24e8414b9b07decb 2017-04-15  7
252104 air_24e8414b9b07decb 2017-04-18  6
252105 air_24e8414b9b07decb 2017-04-19  6
252106 air_24e8414b9b07decb 2017-04-20  7
252107 air_24e8414b9b07decb 2017-04-21  8
252108 air_24e8414b9b07decb 2017-04-22  5

date_info:
- Contains 517 calendar_date values, from 2016-01-01 to 2017-05-31

In [42]:
date_info

    calendar_date day_of_week holiday_flg
1   2016-01-01    Friday      1
2   2016-01-02    Saturday    1
3   2016-01-03    Sunday      1
4   2016-01-04    Monday      0
5   2016-01-05    Tuesday     0
6   2016-01-06    Wednesday   0
7   2016-01-07    Thursday    0
8   2016-01-08    Friday      0
9   2016-01-09    Saturday    0
10  2016-01-10    Sunday      0
11  2016-01-11    Monday      1
12  2016-01-12    Tuesday     0
13  2016-01-13    Wednesday   0
14  2016-01-14    Thursday    0
15  2016-01-15    Friday      0
16  2016-01-16    Saturday    0
17  2016-01-17    Sunday      0
18  2016-01-18    Monday      0
19  2016-01-19    Tuesday     0
20  2016-01-20    Wednesday   0
21  2016-01-21    Thursday    0
22  2016-01-22    Friday      0
23  2016-01-23    Saturday    0
24  2016-01-24    Sunday      0
25  2016-01-25    Monday      0
26  2016-01-26    Tuesday     0
27  2016-01-27    Wednesday   0
28  2016-01-28    Thursday    0
29  2016-01-29    Friday      0
30  2016-01-30    Saturday    0
... ...           ...         ...
488 2017-05-02    Tuesday     0
489 2017-05-03    Wednesday   1
490 2017-05-04    Thursday    1
491 2017-05-05    Friday      1
492 2017-05-06    Saturday    0
493 2017-05-07    Sunday      0
494 2017-05-08    Monday      0
495 2017-05-09    Tuesday     0
496 2017-05-10    Wednesday   0
497 2017-05-11    Thursday    0
498 2017-05-12    Friday      0
499 2017-05-13    Saturday    0
500 2017-05-14    Sunday      0
501 2017-05-15    Monday      0
502 2017-05-16    Tuesday     0
503 2017-05-17    Wednesday   0
504 2017-05-18    Thursday    0
505 2017-05-19    Friday      0
506 2017-05-20    Saturday    0
507 2017-05-21    Sunday      0
508 2017-05-22    Monday      0
509 2017-05-23    Tuesday     0
510 2017-05-24    Wednesday   0
511 2017-05-25    Thursday    0
512 2017-05-26    Friday      0
513 2017-05-27    Saturday    0
514 2017-05-28    Sunday      0
515 2017-05-29    Monday      0
516 2017-05-30    Tuesday     0
517 2017-05-31    Wednesday   0

#### Using the package/library **'questionr'** we can use the function **'freq'** to check the frequency of each element

Observations:
- Show information about 829 restaurants
- We have restaurants that have been open almost every day, to restaurants that have only been open 20 days in a 477 day measurement period
- The restaurant that have been open more days in a period of 477 days is "air_5c817ef28f236bdf"

In [43]:
freq(air_visit$air_store_id, sort = "dec")

                     n   %   val%
air_5c817ef28f236bdf 477 0.2 0.2
air_36bcf77d3382d36e 476 0.2 0.2
air_a083834e7ffe187e 476 0.2 0.2
air_d97dabf7aae60da5 476 0.2 0.2
air_232dcee6f7c51d37 475 0.2 0.2
air_60a7057184ec7ec7 475 0.2 0.2
air_71903025d39a4571 475 0.2 0.2
air_7a946aada80376a4 474 0.2 0.2
air_883ca28ef0ed3d55 474 0.2 0.2
air_4cca5666eaf5c709 473 0.2 0.2
air_cb7467aed805e7fe 473 0.2 0.2
air_d0e8a085d8dc83aa 473 0.2 0.2
air_04341b588bde96cd 472 0.2 0.2
air_3c05c8f26c611eb9 472 0.2 0.2
air_6b15edd1b4fbb96a 472 0.2 0.2
air_dea0655f96947922 472 0.2 0.2
air_fe22ef5a9cbef123 472 0.2 0.2
air_39dccf7df20b1c6a 471 0.2 0.2
air_7cf5a02c0e01b647 471 0.2 0.2
air_ba495cccc8f0f237 471 0.2 0.2
air_287d2de7d3c93406 470 0.2 0.2
air_2b8b29ddfd35018e 470 0.2 0.2
air_536043fcf1a4f8a4 470 0.2 0.2
air_638c35eb25e53eea 470 0.2 0.2
air_640cf4835f0d9ba3 470 0.2 0.2
air_8c119d1f16049f20 470 0.2 0.2
air_e270aff84ac7e4c8 470 0.2 0.2
air_f6b2489ccf873c3b 470 0.2 0.2
air_383f5b2f8d345a49 469 0.2 0.2
air_4d71826793c09b22 469 0.2 0.2
...                  ... ... ...
air_e00fe7853c0100d6 149 0.1 0.1
air_1f34e9beded2231a 148 0.1 0.1
air_0ead98dd07e7a82a 138 0.1 0.1
air_fb44f566d4f64a4e 134 0.1 0.1
air_ef47430bcd6f6a89 132 0.1 0.1
air_e42bdc3377d1eee7 123 0.0 0.0
air_965b2e0cf4119003 121 0.0 0.0
air_0328696196e46f18 116 0.0 0.0
air_17a6ab40f97fd4d8 115 0.0 0.0
air_4b55d8aea1d2b395 114 0.0 0.0
air_31c753b48a657b6c 111 0.0 0.0
air_2a485b92210c98b5 101 0.0 0.0
air_d63cfa6d6ab78446  97 0.0 0.0
air_9cf2f1ba86229773  94 0.0 0.0
air_7420042ff75f9aca  90 0.0 0.0
air_28dbe91c4c9656be  83 0.0 0.0
air_6b65745d432fd77f  81 0.0 0.0
air_2703dcb33192b181  79 0.0 0.0
air_52a08ef3efdb4bb0  72 0.0 0.0
air_9c6787aa03a45586  70 0.0 0.0
air_8110d68cc869b85e  69 0.0 0.0
air_bb4ff06cd661ee9b  66 0.0 0.0
air_8e8f42f047537154  62 0.0 0.0
air_8e492076a1179383  54 0.0 0.0
air_cf5ab75a0afb8af9  53 0.0 0.0
air_1c0b150f9e696a5f  51 0.0 0.0
air_a17f0778617c76e2  47 0.0 0.0
air_789103bf53b8096b  41 0.0 0.0
air_a9a380530c1e121f  40 0.0 0.0
air_900d755ebd2f7bbd  20 0.0 0.0

We extract the information about the "air_5c817ef28f236bdf" restaurant from the "air_visit" dataset
- We can see that it starts on 2016-01-02 and finish on 2017-04-22 with 477 values
- We must check if in that period there are 477 days, to check if we miss any day.  As we see in the dataset description "The training set omits days where the restaurants were closed"
- We must take into account the Time Series definition "a time series is a sequence taken at successive **equally spaced** points in time".  If there are days "omitted" the sequence is not equally spaced
- We must find if there are any "omitted day" and fill it with 0 visitors

In [44]:
air_visit_5c817ef28f236bdf <- air_visit[air_visit$air_store_id == "air_5c817ef28f236bdf", 
                                        c("air_store_id","visit_date","visitors")]
air_visit_5c817ef28f236bdf

       air_store_id         visit_date visitors
158603 air_5c817ef28f236bdf 2016-01-02 24
158604 air_5c817ef28f236bdf 2016-01-03 49
158605 air_5c817ef28f236bdf 2016-01-04 10
158606 air_5c817ef28f236bdf 2016-01-05  2
158607 air_5c817ef28f236bdf 2016-01-06  9
158608 air_5c817ef28f236bdf 2016-01-07 15
158609 air_5c817ef28f236bdf 2016-01-08 36
158610 air_5c817ef28f236bdf 2016-01-09 44
158611 air_5c817ef28f236bdf 2016-01-10 25
158612 air_5c817ef28f236bdf 2016-01-11  7
158613 air_5c817ef28f236bdf 2016-01-12  6
158614 air_5c817ef28f236bdf 2016-01-13  1
158615 air_5c817ef28f236bdf 2016-01-14  7
158616 air_5c817ef28f236bdf 2016-01-15 32
158617 air_5c817ef28f236bdf 2016-01-16 49
158618 air_5c817ef28f236bdf 2016-01-17 26
158619 air_5c817ef28f236bdf 2016-01-18  6
158620 air_5c817ef28f236bdf 2016-01-19 12
158621 air_5c817ef28f236bdf 2016-01-20 24
158622 air_5c817ef28f236bdf 2016-01-21 37
158623 air_5c817ef28f236bdf 2016-01-22 47
158624 air_5c817ef28f236bdf 2016-01-23 42
158625 air_5c817ef28f236bdf 2016-01-24 30
158626 air_5c817ef28f236bdf 2016-01-25  7
158627 air_5c817ef28f236bdf 2016-01-26  9
158628 air_5c817ef28f236bdf 2016-01-27  5
158629 air_5c817ef28f236bdf 2016-01-28 16
158630 air_5c817ef28f236bdf 2016-01-29 50
158631 air_5c817ef28f236bdf 2016-01-30 46
158632 air_5c817ef28f236bdf 2016-01-31 50
...    ...                  ...        ...
159050 air_5c817ef28f236bdf 2017-03-24 70
159051 air_5c817ef28f236bdf 2017-03-25 95
159052 air_5c817ef28f236bdf 2017-03-26 33
159053 air_5c817ef28f236bdf 2017-03-27 48
159054 air_5c817ef28f236bdf 2017-03-28 21
159055 air_5c817ef28f236bdf 2017-03-29 39
159056 air_5c817ef28f236bdf 2017-03-30 36
159057 air_5c817ef28f236bdf 2017-03-31 79
159058 air_5c817ef28f236bdf 2017-04-01 67
159059 air_5c817ef28f236bdf 2017-04-02 55
159060 air_5c817ef28f236bdf 2017-04-03 21
159061 air_5c817ef28f236bdf 2017-04-04 45
159062 air_5c817ef28f236bdf 2017-04-05 44
159063 air_5c817ef28f236bdf 2017-04-06 22
159064 air_5c817ef28f236bdf 2017-04-07 56
159065 air_5c817ef28f236bdf 2017-04-08 71
159066 air_5c817ef28f236bdf 2017-04-09 40
159067 air_5c817ef28f236bdf 2017-04-10 26
159068 air_5c817ef28f236bdf 2017-04-11 23
159069 air_5c817ef28f236bdf 2017-04-12 44
159070 air_5c817ef28f236bdf 2017-04-13 19
159071 air_5c817ef28f236bdf 2017-04-14 55
159072 air_5c817ef28f236bdf 2017-04-15 69
159073 air_5c817ef28f236bdf 2017-04-16 60
159074 air_5c817ef28f236bdf 2017-04-17 18
159075 air_5c817ef28f236bdf 2017-04-18 30
159076 air_5c817ef28f236bdf 2017-04-19 20
159077 air_5c817ef28f236bdf 2017-04-20 22
159078 air_5c817ef28f236bdf 2017-04-21 71
159079 air_5c817ef28f236bdf 2017-04-22 97

#### Using the package/library "dplyr" we extract from the "date_info" dataset the period that the "air_5c817ef28f236bdf" restaurant is open (from 2016-01-02 to 2017-04-22)

In [45]:
date_info_air_5c817ef28f236bdf <- date_info %>%
    left_join(air_visit_5c817ef28f236bdf, by = c(calendar_date = 'visit_date')) %>%
    rename(visitors = 'visitors')
date_info_air_5c817ef28f236bdf

    calendar_date day_of_week holiday_flg air_store_id         visitors
1   2016-01-01    Friday      1           NA                   NA
2   2016-01-02    Saturday    1           air_5c817ef28f236bdf 24
3   2016-01-03    Sunday      1           air_5c817ef28f236bdf 49
4   2016-01-04    Monday      0           air_5c817ef28f236bdf 10
5   2016-01-05    Tuesday     0           air_5c817ef28f236bdf  2
6   2016-01-06    Wednesday   0           air_5c817ef28f236bdf  9
7   2016-01-07    Thursday    0           air_5c817ef28f236bdf 15
8   2016-01-08    Friday      0           air_5c817ef28f236bdf 36
9   2016-01-09    Saturday    0           air_5c817ef28f236bdf 44
10  2016-01-10    Sunday      0           air_5c817ef28f236bdf 25
11  2016-01-11    Monday      1           air_5c817ef28f236bdf  7
12  2016-01-12    Tuesday     0           air_5c817ef28f236bdf  6
13  2016-01-13    Wednesday   0           air_5c817ef28f236bdf  1
14  2016-01-14    Thursday    0           air_5c817ef28f236bdf  7
15  2016-01-15    Friday      0           air_5c817ef28f236bdf 32
16  2016-01-16    Saturday    0           air_5c817ef28f236bdf 49
17  2016-01-17    Sunday      0           air_5c817ef28f236bdf 26
18  2016-01-18    Monday      0           air_5c817ef28f236bdf  6
19  2016-01-19    Tuesday     0           air_5c817ef28f236bdf 12
20  2016-01-20    Wednesday   0           air_5c817ef28f236bdf 24
21  2016-01-21    Thursday    0           air_5c817ef28f236bdf 37
22  2016-01-22    Friday      0           air_5c817ef28f236bdf 47
23  2016-01-23    Saturday    0           air_5c817ef28f236bdf 42
24  2016-01-24    Sunday      0           air_5c817ef28f236bdf 30
25  2016-01-25    Monday      0           air_5c817ef28f236bdf  7
26  2016-01-26    Tuesday     0           air_5c817ef28f236bdf  9
27  2016-01-27    Wednesday   0           air_5c817ef28f236bdf  5
28  2016-01-28    Thursday    0           air_5c817ef28f236bdf 16
29  2016-01-29    Friday      0           air_5c817ef28f236bdf 50
30  2016-01-30    Saturday    0           air_5c817ef28f236bdf 46
... ...           ...         ...         ...                  ...
488 2017-05-02    Tuesday     0           NA                   NA
489 2017-05-03    Wednesday   1           NA                   NA
490 2017-05-04    Thursday    1           NA                   NA
491 2017-05-05    Friday      1           NA                   NA
492 2017-05-06    Saturday    0           NA                   NA
493 2017-05-07    Sunday      0           NA                   NA
494 2017-05-08    Monday      0           NA                   NA
495 2017-05-09    Tuesday     0           NA                   NA
496 2017-05-10    Wednesday   0           NA                   NA
497 2017-05-11    Thursday    0           NA                   NA
498 2017-05-12    Friday      0           NA                   NA
499 2017-05-13    Saturday    0           NA                   NA
500 2017-05-14    Sunday      0           NA                   NA
501 2017-05-15    Monday      0           NA                   NA
502 2017-05-16    Tuesday     0           NA                   NA
503 2017-05-17    Wednesday   0           NA                   NA
504 2017-05-18    Thursday    0           NA                   NA
505 2017-05-19    Friday      0           NA                   NA
506 2017-05-20    Saturday    0           NA                   NA
507 2017-05-21    Sunday      0           NA                   NA
508 2017-05-22    Monday      0           NA                   NA
509 2017-05-23    Tuesday     0           NA                   NA
510 2017-05-24    Wednesday   0           NA                   NA
511 2017-05-25    Thursday    0           NA                   NA
512 2017-05-26    Friday      0           NA                   NA
513 2017-05-27    Saturday    0           NA                   NA
514 2017-05-28    Sunday      0           NA                   NA
515 2017-05-29    Monday      0           NA                   NA
516 2017-05-30    Tuesday     0           NA                   NA
517 2017-05-31    Wednesday   0           NA                   NA

- Extract the "air_store_id" column from the dataset that is redundant
- Check that "calendar_date" is in chr (character) format, we must convert to date format

In [46]:
date_info_air_ <- select(date_info_air_5c817ef28f236bdf, -air_store_id)
date_info_air_

    calendar_date day_of_week holiday_flg visitors
1   2016-01-01    Friday      1           NA
2   2016-01-02    Saturday    1           24
3   2016-01-03    Sunday      1           49
4   2016-01-04    Monday      0           10
5   2016-01-05    Tuesday     0            2
6   2016-01-06    Wednesday   0            9
7   2016-01-07    Thursday    0           15
8   2016-01-08    Friday      0           36
9   2016-01-09    Saturday    0           44
10  2016-01-10    Sunday      0           25
11  2016-01-11    Monday      1            7
12  2016-01-12    Tuesday     0            6
13  2016-01-13    Wednesday   0            1
14  2016-01-14    Thursday    0            7
15  2016-01-15    Friday      0           32
16  2016-01-16    Saturday    0           49
17  2016-01-17    Sunday      0           26
18  2016-01-18    Monday      0            6
19  2016-01-19    Tuesday     0           12
20  2016-01-20    Wednesday   0           24
21  2016-01-21    Thursday    0           37
22  2016-01-22    Friday      0           47
23  2016-01-23    Saturday    0           42
24  2016-01-24    Sunday      0           30
25  2016-01-25    Monday      0            7
26  2016-01-26    Tuesday     0            9
27  2016-01-27    Wednesday   0            5
28  2016-01-28    Thursday    0           16
29  2016-01-29    Friday      0           50
30  2016-01-30    Saturday    0           46
... ...           ...         ...         ...
488 2017-05-02    Tuesday     0           NA
489 2017-05-03    Wednesday   1           NA
490 2017-05-04    Thursday    1           NA
491 2017-05-05    Friday      1           NA
492 2017-05-06    Saturday    0           NA
493 2017-05-07    Sunday      0           NA
494 2017-05-08    Monday      0           NA
495 2017-05-09    Tuesday     0           NA
496 2017-05-10    Wednesday   0           NA
497 2017-05-11    Thursday    0           NA
498 2017-05-12    Friday      0           NA
499 2017-05-13    Saturday    0           NA
500 2017-05-14    Sunday      0           NA
501 2017-05-15    Monday      0           NA
502 2017-05-16    Tuesday     0           NA
503 2017-05-17    Wednesday   0           NA
504 2017-05-18    Thursday    0           NA
505 2017-05-19    Friday      0           NA
506 2017-05-20    Saturday    0           NA
507 2017-05-21    Sunday      0           NA
508 2017-05-22    Monday      0           NA
509 2017-05-23    Tuesday     0           NA
510 2017-05-24    Wednesday   0           NA
511 2017-05-25    Thursday    0           NA
512 2017-05-26    Friday      0           NA
513 2017-05-27    Saturday    0           NA
514 2017-05-28    Sunday      0           NA
515 2017-05-29    Monday      0           NA
516 2017-05-30    Tuesday     0           NA
517 2017-05-31    Wednesday   0           NA

Using the "mutate" function of dplyr, now "calendar_date" have a date format

In [47]:
date_info_air_ %>% 
    mutate(calendar_date = as.Date(calendar_date, format = "%Y-%m-%d"))

    calendar_date day_of_week holiday_flg visitors
1   2016-01-01    Friday      1           NA
2   2016-01-02    Saturday    1           24
3   2016-01-03    Sunday      1           49
4   2016-01-04    Monday      0           10
5   2016-01-05    Tuesday     0            2
6   2016-01-06    Wednesday   0            9
7   2016-01-07    Thursday    0           15
8   2016-01-08    Friday      0           36
9   2016-01-09    Saturday    0           44
10  2016-01-10    Sunday      0           25
11  2016-01-11    Monday      1            7
12  2016-01-12    Tuesday     0            6
13  2016-01-13    Wednesday   0            1
14  2016-01-14    Thursday    0            7
15  2016-01-15    Friday      0           32
16  2016-01-16    Saturday    0           49
17  2016-01-17    Sunday      0           26
18  2016-01-18    Monday      0            6
19  2016-01-19    Tuesday     0           12
20  2016-01-20    Wednesday   0           24
21  2016-01-21    Thursday    0           37
22  2016-01-22    Friday      0           47
23  2016-01-23    Saturday    0           42
24  2016-01-24    Sunday      0           30
25  2016-01-25    Monday      0            7
26  2016-01-26    Tuesday     0            9
27  2016-01-27    Wednesday   0            5
28  2016-01-28    Thursday    0           16
29  2016-01-29    Friday      0           50
30  2016-01-30    Saturday    0           46
... ...           ...         ...         ...
488 2017-05-02    Tuesday     0           NA
489 2017-05-03    Wednesday   1           NA
490 2017-05-04    Thursday    1           NA
491 2017-05-05    Friday      1           NA
492 2017-05-06    Saturday    0           NA
493 2017-05-07    Sunday      0           NA
494 2017-05-08    Monday      0           NA
495 2017-05-09    Tuesday     0           NA
496 2017-05-10    Wednesday   0           NA
497 2017-05-11    Thursday    0           NA
498 2017-05-12    Friday      0           NA
499 2017-05-13    Saturday    0           NA
500 2017-05-14    Sunday      0           NA
501 2017-05-15    Monday      0           NA
502 2017-05-16    Tuesday     0           NA
503 2017-05-17    Wednesday   0           NA
504 2017-05-18    Thursday    0           NA
505 2017-05-19    Friday      0           NA
506 2017-05-20    Saturday    0           NA
507 2017-05-21    Sunday      0           NA
508 2017-05-22    Monday      0           NA
509 2017-05-23    Tuesday     0           NA
510 2017-05-24    Wednesday   0           NA
511 2017-05-25    Thursday    0           NA
512 2017-05-26    Friday      0           NA
513 2017-05-27    Saturday    0           NA
514 2017-05-28    Sunday      0           NA
515 2017-05-29    Monday      0           NA
516 2017-05-30    Tuesday     0           NA
517 2017-05-31    Wednesday   0           NA

Now we have the final dataset, as we see the number of days from 2016-01-02 to 2017-04-22 are the same as the information provided by the "air_5c817ef28f236bdf" restaurant (477 days), so they don't close any day in that period

In [52]:
date_info_air_final <- date_info_air_[(date_info_air_$calendar_date > "2016-01-01" 
                                       & date_info_air_$calendar_date < "2017-04-23"),]
date_info_air_final

    calendar_date day_of_week holiday_flg visitors
2   2016-01-02    Saturday    1           24
3   2016-01-03    Sunday      1           49
4   2016-01-04    Monday      0           10
5   2016-01-05    Tuesday     0            2
6   2016-01-06    Wednesday   0            9
7   2016-01-07    Thursday    0           15
8   2016-01-08    Friday      0           36
9   2016-01-09    Saturday    0           44
10  2016-01-10    Sunday      0           25
11  2016-01-11    Monday      1            7
12  2016-01-12    Tuesday     0            6
13  2016-01-13    Wednesday   0            1
14  2016-01-14    Thursday    0            7
15  2016-01-15    Friday      0           32
16  2016-01-16    Saturday    0           49
17  2016-01-17    Sunday      0           26
18  2016-01-18    Monday      0            6
19  2016-01-19    Tuesday     0           12
20  2016-01-20    Wednesday   0           24
21  2016-01-21    Thursday    0           37
22  2016-01-22    Friday      0           47
23  2016-01-23    Saturday    0           42
24  2016-01-24    Sunday      0           30
25  2016-01-25    Monday      0            7
26  2016-01-26    Tuesday     0            9
27  2016-01-27    Wednesday   0            5
28  2016-01-28    Thursday    0           16
29  2016-01-29    Friday      0           50
30  2016-01-30    Saturday    0           46
31  2016-01-31    Sunday      0           50
... ...           ...         ...         ...
449 2017-03-24    Friday      0           70
450 2017-03-25    Saturday    0           95
451 2017-03-26    Sunday      0           33
452 2017-03-27    Monday      0           48
453 2017-03-28    Tuesday     0           21
454 2017-03-29    Wednesday   0           39
455 2017-03-30    Thursday    0           36
456 2017-03-31    Friday      0           79
457 2017-04-01    Saturday    0           67
458 2017-04-02    Sunday      0           55
459 2017-04-03    Monday      0           21
460 2017-04-04    Tuesday     0           45
461 2017-04-05    Wednesday   0           44
462 2017-04-06    Thursday    0           22
463 2017-04-07    Friday      0           56
464 2017-04-08    Saturday    0           71
465 2017-04-09    Sunday      0           40
466 2017-04-10    Monday      0           26
467 2017-04-11    Tuesday     0           23
468 2017-04-12    Wednesday   0           44
469 2017-04-13    Thursday    0           19
470 2017-04-14    Friday      0           55
471 2017-04-15    Saturday    0           69
472 2017-04-16    Sunday      0           60
473 2017-04-17    Monday      0           18
474 2017-04-18    Tuesday     0           30
475 2017-04-19    Wednesday   0           20
476 2017-04-20    Thursday    0           22
477 2017-04-21    Friday      0           71
478 2017-04-22    Saturday    0           97

In [54]:
write.csv(date_info_air_final,"C://MBD//TimeSeries_R_dplyr_questionr.csv", row.names = FALSE)